#spring.application.name=demo
#spring.datasource.url=jdbc:mysql://192.168.72.66:3310/employee_directory
#spring.datasource.username=springstudent
#spring.datasource.password=springstudent

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/contact_directory
    username: root
    password: praful1604
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers:true
        dialect:org.hibernate.dialect.MySQLDialect
        format_sql:true
  servlet:
    multiport:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB

  mvc:
    throw-exception-if-no-handler-found: true
    async:
      request-timeout: 3600000

server:
  port: 8080
  error:
    path: /user/error
    whitelabel:
      enabled: false
